# Generated by Django 6.0.1 on 2026-01-29 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niche', models.CharField(choices=[('fashion', 'Sustainable Fashion'), ('lifestyle', 'Eco-Lifestyle'), ('art', 'Art & Culture'), ('handmade', 'Handmade & DIY'), ('wellness', 'Wellness & Beauty'), ('other', 'Other')], max_length=50)),
                ('bio', models.TextField(help_text='Your professional bio', max_length=1000)),
                ('follower_count', models.IntegerField(default=0)),
                ('instagram_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram_followers', models.IntegerField(default=0)),
                ('youtube_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube_subscribers', models.IntegerField(default=0)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('personal_website', models.URLField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_collaborations', models.IntegerField(default=0)),
                ('collaboration_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Collaboration fee as percentage', max_digits=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Influencer Profile',
                'verbose_name_plural': 'Influencer Profiles',
                'db_table': 'influencers_profile',
            },
        ),
    ]
