# Generated by Django 6.0.1 on 2026-01-29 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artisans', '0001_initial'),
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('flat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('total_products_promoted', models.IntegerField(default=0)),
                ('total_sales_generated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('posts_published', models.IntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_collaborations', to='artisans.artisanprofile')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_collaborations', to='influencers.influencerprofile')),
            ],
            options={
                'verbose_name': 'Active Collaboration',
                'verbose_name_plural': 'Active Collaborations',
                'db_table': 'collaborations_active',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollaborationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='collaboration_posts/')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('blog', 'Blog')], default='instagram', max_length=50)),
                ('url', models.URLField(blank=True, help_text='Link to the post', null=True)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='collaborations.activecollaboration')),
            ],
            options={
                'verbose_name': 'Collaboration Post',
                'verbose_name_plural': 'Collaboration Posts',
                'db_table': 'collaborations_post',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('proposed_terms', models.TextField(help_text='Terms of collaboration')),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Influencer commission percentage on sales', max_digits=5, null=True)),
                ('flat_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Flat rate for collaboration', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('message_from_influencer', models.TextField(blank=True, null=True)),
                ('response_from_artisan', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='collaboration_files/')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='artisans.artisanprofile')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='influencers.influencerprofile')),
            ],
            options={
                'verbose_name': 'Collaboration Request',
                'verbose_name_plural': 'Collaboration Requests',
                'db_table': 'collaborations_request',
                'ordering': ['-requested_at'],
                'unique_together': {('influencer', 'artisan')},
            },
        ),
        migrations.AddField(
            model_name='activecollaboration',
            name='collaboration_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaboration', to='collaborations.collaborationrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='activecollaboration',
            unique_together={('influencer', 'artisan')},
        ),
    ]
