# Generated by Django 6.0.1 on 2026-01-29 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('craft_type', models.CharField(choices=[('textiles', 'Textiles & Weaving'), ('pottery', 'Pottery & Ceramics'), ('jewelry', 'Jewelry & Accessories'), ('woodwork', 'Woodwork & Carpentry'), ('metalwork', 'Metalwork'), ('painting', 'Painting & Art'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(help_text='Detailed description of your craft')),
                ('years_of_experience', models.IntegerField(default=0)),
                ('workshop_location', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('instagram_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_products', models.IntegerField(default=0)),
                ('total_sales', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artisan_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artisan Profile',
                'verbose_name_plural': 'Artisan Profiles',
                'db_table': 'artisans_profile',
            },
        ),
    ]
