# Generated by Django 6.0.1 on 2026-01-30 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0002_artisanteam_artisanprofile_team_artisanteammember'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='artisans.artisanteam'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['team', 'status'], name='products_pr_team_id_21af15_idx'),
        ),
    ]
