# Generated by Django 5.0.7 on 2026-01-31 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_clamp_prices_to_inr'),
        ('products', '0003_assign_default_category'),
    ]

    operations = [
    ]
